### ISSUE TITLE
Installation issues with PyQt5

### ISSUE THREAD

**Issue by Vignesh1230** [healthonrails/annolid#18]
Having PyQt5 version issues when installing and running annolid.
Ive attached the terminal logs. Annolid was installed in a new condo environment.

Any ideas on how to fix this?

```
(annotate) cerebro0@cerebro:~$ git clone --recurse-submodules https://github.com/healthonrails/annolid.git
Cloning into 'annolid'...
remote: Enumerating objects: 2570, done.
remote: Counting objects: 100% (873/873), done.
remote: Compressing objects: 100% (502/502), done.
remote: Total 2570 (delta 641), reused 580 (delta 361), pack-reused 1697
Receiving objects: 100% (2570/2570), 106.42 MiB | 1.37 MiB/s, done.
Resolving deltas: 100% (1676/1676), done.
Submodule 'annolid/detector/yolov5' (https://github.com/healthonrails/yolov5.git) registered for path 'annolid/detector/yolov5'
Submodule 'annolid/segmentation/SCOPS' (https://github.com/healthonrails/SCOPS.git) registered for path 'annolid/segmentation/SCOPS'
Submodule 'annolid/segmentation/yolact' (https://github.com/healthonrails/yolact.git) registered for path 'annolid/segmentation/yolact'
Cloning into '/home/cerebro0/annolid/annolid/detector/yolov5'...
remote: Enumerating objects: 2586, done.
remote: Total 2586 (delta 0), reused 0 (delta 0), pack-reused 2586
Receiving objects: 100% (2586/2586), 18.85 MiB | 1.38 MiB/s, done.
Resolving deltas: 100% (1708/1708), done.
Cloning into '/home/cerebro0/annolid/annolid/segmentation/SCOPS'...
remote: Enumerating objects: 71, done.
remote: Counting objects: 100% (1/1), done.
remote: Total 71 (delta 0), reused 0 (delta 0), pack-reused 70
Cloning into '/home/cerebro0/annolid/annolid/segmentation/yolact'...
remote: Enumerating objects: 3060, done.
remote: Total 3060 (delta 0), reused 0 (delta 0), pack-reused 3060
Receiving objects: 100% (3060/3060), 62.26 MiB | 1.26 MiB/s, done.
Resolving deltas: 100% (2074/2074), done.
Submodule path 'annolid/detector/yolov5': checked out '463961eee59f00187bb1abf69f39275c34b9adc8'
Submodule path 'annolid/segmentation/SCOPS': checked out '05da7e4690bd9e1edabc93ecb9c44207ea20a76b'
Submodule path 'annolid/segmentation/yolact': checked out 'a69499e14b4cdf52f8ca904c41a1bf5c1012f300'
(annotate) cerebro0@cerebro:~$ cd annolid/
(annotate) cerebro0@cerebro:~/annolid$ conda create --name=annotation python=3.7
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/cerebro0/miniconda3/envs/annotation

  added / updated specs:
    - python=3.7


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2021.5.30          |   py37h06a4308_0         139 KB
    pip-21.1.3                 |   py37h06a4308_0         1.8 MB
    python-3.7.10              |       h12debd9_4        44.0 MB
    setuptools-52.0.0          |   py37h06a4308_0         710 KB
    ------------------------------------------------------------
                                           Total:        46.6 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-4.5-1_gnu
  ca-certificates    pkgs/main/linux-64::ca-certificates-2021.7.5-h06a4308_1
  certifi            pkgs/main/linux-64::certifi-2021.5.30-py37h06a4308_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.35.1-h7274673_9
  libffi             pkgs/main/linux-64::libffi-3.3-he6710b0_2
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.3.0-h5101ec6_17
  libgomp            pkgs/main/linux-64::libgomp-9.3.0-h5101ec6_17
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.3.0-hd4cf53a_17
  ncurses            pkgs/main/linux-64::ncurses-6.2-he6710b0_1
  openssl            pkgs/main/linux-64::openssl-1.1.1k-h27cfd23_0
  pip                pkgs/main/linux-64::pip-21.1.3-py37h06a4308_0
  python             pkgs/main/linux-64::python-3.7.10-h12debd9_4
  readline           pkgs/main/linux-64::readline-8.1-h27cfd23_0
  setuptools         pkgs/main/linux-64::setuptools-52.0.0-py37h06a4308_0
  sqlite             pkgs/main/linux-64::sqlite-3.36.0-hc218d9a_0
  tk                 pkgs/main/linux-64::tk-8.6.10-hbc83047_0
  wheel              pkgs/main/noarch::wheel-0.36.2-pyhd3eb1b0_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7b6447c_0
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3


Proceed ([y]/n)? y


Downloading and Extracting Packages
python-3.7.10        | 44.0 MB   | ################################################################################################## | 100%
certifi-2021.5.30    | 139 KB    | ################################################################################################## | 100%
pip-21.1.3           | 1.8 MB    | ################################################################################################## | 100%
setuptools-52.0.0    | 710 KB    | ################################################################################################## | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate annotation
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(annotate) cerebro0@cerebro:~/annolid$ conda activate annotation
(annotation) cerebro0@cerebro:~/annolid$ pip3 install -e .
Obtaining file:///home/cerebro0/annolid
Collecting numpy>=1.18.2
  Downloading numpy-1.21.1-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.7 MB)
     |████████████████████████████████| 15.7 MB 580 kB/s
Collecting scipy>=1.5.2
  Downloading scipy-1.7.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (28.5 MB)
     |████████████████████████████████| 28.5 MB 1.9 MB/s
Collecting easydict>=1.9
  Using cached easydict-1.9.tar.gz (6.4 kB)
Collecting opencv-python==4.1.2.30
  Downloading opencv_python-4.1.2.30-cp37-cp37m-manylinux1_x86_64.whl (28.3 MB)
     |████████████████████████████████| 28.3 MB 1.4 MB/s
Collecting opencv-contrib-python==4.1.2.30
  Downloading opencv_contrib_python-4.1.2.30-cp37-cp37m-manylinux1_x86_64.whl (34.3 MB)
     |████████████████████████████████| 34.3 MB 1.7 MB/s
Collecting opencv-python-headless==4.1.2.30
  Downloading opencv_python_headless-4.1.2.30-cp37-cp37m-manylinux1_x86_64.whl (21.8 MB)
     |████████████████████████████████| 21.8 MB 303 kB/s
Collecting PyYAML>=5.3
  Downloading PyYAML-5.4.1-cp37-cp37m-manylinux1_x86_64.whl (636 kB)
     |████████████████████████████████| 636 kB 961 kB/s
Collecting labelme>=4.5.6
  Using cached labelme-4.5.9.tar.gz (1.5 MB)
Collecting decord>=0.4.0
  Using cached decord-0.6.0-py3-none-manylinux2010_x86_64.whl (13.6 MB)
Collecting torch>=1.4.0
  Downloading torch-1.9.0-cp37-cp37m-manylinux1_x86_64.whl (831.4 MB)
     |████████████████████████████████| 831.4 MB 2.7 kB/s
Collecting torchvision>=0.5.0
  Downloading torchvision-0.10.0-cp37-cp37m-manylinux1_x86_64.whl (22.1 MB)
     |████████████████████████████████| 22.1 MB 1.2 MB/s
Collecting pandas>=1.1.3
  Downloading pandas-1.3.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.5 MB)
     |████████████████████████████████| 11.5 MB 1.5 MB/s
Collecting pycocotools>=2.0.2
  Using cached pycocotools-2.0.2.tar.gz (23 kB)
Collecting tensorboard>=2.3.0
  Using cached tensorboard-2.5.0-py3-none-any.whl (6.0 MB)
Collecting PyQtWebEngine>=5.15.1
  Using cached PyQtWebEngine-5.15.4-cp36.cp37.cp38.cp39-abi3-manylinux2014_x86_64.whl (229 kB)
Collecting imgviz>=0.11.0
  Using cached imgviz-1.2.6.tar.gz (7.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting matplotlib<3.3
  Downloading matplotlib-3.2.2-cp37-cp37m-manylinux1_x86_64.whl (12.4 MB)
     |████████████████████████████████| 12.4 MB 1.5 MB/s
Collecting Pillow>=2.8.0
  Downloading Pillow-8.3.1-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (3.0 MB)
     |████████████████████████████████| 3.0 MB 1.3 MB/s
Collecting qtpy
  Using cached QtPy-1.9.0-py2.py3-none-any.whl (54 kB)
Collecting termcolor
  Using cached termcolor-1.1.0.tar.gz (3.9 kB)
Collecting PyQt5!=5.15.3,!=5.15.4
  Using cached PyQt5-5.15.2-5.15.2-cp35.cp36.cp37.cp38.cp39-abi3-manylinux2014_x86_64.whl (68.3 MB)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.3.1-cp37-cp37m-manylinux1_x86_64.whl (1.1 MB)
     |████████████████████████████████| 1.1 MB 1.7 MB/s
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting python-dateutil>=2.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting pytz>=2017.3
  Using cached pytz-2021.1-py2.py3-none-any.whl (510 kB)
Requirement already satisfied: setuptools>=18.0 in /home/cerebro0/miniconda3/envs/annotation/lib/python3.7/site-packages (from pycocotools>=2.0.2->annolid==1.0.1) (52.0.0.post20210125)
Collecting cython>=0.27.3
  Using cached Cython-0.29.24-cp37-cp37m-manylinux1_x86_64.whl (2.0 MB)
Collecting PyQt5-sip<13,>=12.8
  Downloading PyQt5_sip-12.9.0-cp37-cp37m-manylinux1_x86_64.whl (317 kB)
     |████████████████████████████████| 317 kB 1.0 MB/s
Collecting PyQtWebEngine>=5.15.1
  Using cached PyQtWebEngine-5.15.3-cp36.cp37.cp38.cp39-abi3-manylinux2014_x86_64.whl (229 kB)
  Using cached PyQtWebEngine-5.15.2-5.15.2-cp35.cp36.cp37.cp38.cp39-abi3-manylinux2014_x86_64.whl (67.7 MB)
Collecting werkzeug>=0.11.15
  Using cached Werkzeug-2.0.1-py3-none-any.whl (288 kB)
Collecting protobuf>=3.6.0
  Downloading protobuf-3.17.3-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (1.0 MB)
     |████████████████████████████████| 1.0 MB 949 kB/s
Collecting absl-py>=0.4
  Using cached absl_py-0.13.0-py3-none-any.whl (132 kB)
Collecting markdown>=2.6.8
  Using cached Markdown-3.3.4-py3-none-any.whl (97 kB)
Collecting requests<3,>=2.21.0
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Requirement already satisfied: wheel>=0.26 in /home/cerebro0/miniconda3/envs/annotation/lib/python3.7/site-packages (from tensorboard>=2.3.0->annolid==1.0.1) (0.36.2)
Collecting google-auth-oauthlib<0.5,>=0.4.1
  Using cached google_auth_oauthlib-0.4.4-py2.py3-none-any.whl (18 kB)
Collecting tensorboard-plugin-wit>=1.6.0
  Using cached tensorboard_plugin_wit-1.8.0-py3-none-any.whl (781 kB)
Collecting tensorboard-data-server<0.7.0,>=0.6.0
  Using cached tensorboard_data_server-0.6.1-py3-none-manylinux2010_x86_64.whl (4.9 MB)
Collecting grpcio>=1.24.3
  Downloading grpcio-1.39.0-cp37-cp37m-manylinux2014_x86_64.whl (4.3 MB)
     |████████████████████████████████| 4.3 MB 1.7 MB/s
Collecting google-auth<2,>=1.6.3
  Using cached google_auth-1.33.1-py2.py3-none-any.whl (152 kB)
Collecting cachetools<5.0,>=2.0.0
  Using cached cachetools-4.2.2-py3-none-any.whl (11 kB)
Collecting pyasn1-modules>=0.2.1
  Using cached pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
Collecting rsa<5,>=3.1.4
  Using cached rsa-4.7.2-py3-none-any.whl (34 kB)
Collecting requests-oauthlib>=0.7.0
  Using cached requests_oauthlib-1.3.0-py2.py3-none-any.whl (23 kB)
Collecting importlib-metadata
  Using cached importlib_metadata-4.6.1-py3-none-any.whl (17 kB)
Collecting pyasn1<0.5.0,>=0.4.6
  Using cached pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
Requirement already satisfied: certifi>=2017.4.17 in /home/cerebro0/miniconda3/envs/annotation/lib/python3.7/site-packages (from requests<3,>=2.21.0->tensorboard>=2.3.0->annolid==1.0.1) (2021.5.30)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.6-py2.py3-none-any.whl (138 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.3-py3-none-any.whl (35 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.2-py3-none-any.whl (59 kB)
Collecting oauthlib>=3.0.0
  Using cached oauthlib-3.1.1-py2.py3-none-any.whl (146 kB)
Collecting typing-extensions
  Using cached typing_extensions-3.10.0.0-py3-none-any.whl (26 kB)
Collecting zipp>=0.5
  Using cached zipp-3.5.0-py3-none-any.whl (5.7 kB)
Building wheels for collected packages: easydict, labelme, imgviz, pycocotools, termcolor
  Building wheel for easydict (setup.py) ... done
  Created wheel for easydict: filename=easydict-1.9-py3-none-any.whl size=6350 sha256=6292f5da84cd6c0a824a4d318864664206fb2e9ddbf9a601fdaca88ba30f9784
  Stored in directory: /home/cerebro0/.cache/pip/wheels/88/96/68/c2be18e7406804be2e593e1c37845f2dd20ac2ce1381ce40b0
  Building wheel for labelme (setup.py) ... done
  Created wheel for labelme: filename=labelme-4.5.9-py3-none-any.whl size=1465422 sha256=e46727a34a9b509710f918d1f2bd2037238b0d6e6e316500db4d31a2959da91c
  Stored in directory: /home/cerebro0/.cache/pip/wheels/1a/69/e0/8e8530643e291ff5b3eeb05568d873ad42b08c15166885a288
  Building wheel for imgviz (PEP 517) ... done
  Created wheel for imgviz: filename=imgviz-1.2.6-py3-none-any.whl size=7674073 sha256=060f4fdd65abd9d811c2ec3e1c6778809ba06757ec02ef69df0ef2575b35e92e
  Stored in directory: /home/cerebro0/.cache/pip/wheels/e6/64/f9/a28eca2133ece5f072f51282577f2f9b7d6d0492eb3d2104dd
  Building wheel for pycocotools (setup.py) ... done
  Created wheel for pycocotools: filename=pycocotools-2.0.2-cp37-cp37m-linux_x86_64.whl size=370269 sha256=bc894d2cefc94c4dad7d38f291a7835fc98d0de7fa5fcfb4796e6d032e5f264b
  Stored in directory: /home/cerebro0/.cache/pip/wheels/bc/cf/1b/e95c99c5f9d1648be3f500ca55e7ce55f24818b0f48336adaf
  Building wheel for termcolor (setup.py) ... done
  Created wheel for termcolor: filename=termcolor-1.1.0-py3-none-any.whl size=4829 sha256=df293290cd596b454a988013d574bf0cd8fd11a82ae5df3d3f2c7dccacab8e17
  Stored in directory: /home/cerebro0/.cache/pip/wheels/3f/e3/ec/8a8336ff196023622fbcb36de0c5a5c218cbb24111d1d4c7f2
Successfully built easydict labelme imgviz pycocotools termcolor
Installing collected packages: urllib3, six, pyasn1, idna, charset-normalizer, zipp, typing-extensions, rsa, requests, python-dateutil, pyparsing, pyasn1-modules, oauthlib, numpy, kiwisolver, cycler, cachetools, requests-oauthlib, PyYAML, PyQt5-sip, Pillow, matplotlib, importlib-metadata, google-auth, werkzeug, torch, termcolor, tensorboard-plugin-wit, tensorboard-data-server, qtpy, pytz, PyQt5, protobuf, markdown, imgviz, grpcio, google-auth-oauthlib, cython, absl-py, torchvision, tensorboard, scipy, PyQtWebEngine, pycocotools, pandas, opencv-python-headless, opencv-python, opencv-contrib-python, labelme, easydict, decord, annolid
  Running setup.py develop for annolid
Successfully installed Pillow-8.3.1 PyQt5-5.15.2 PyQt5-sip-12.9.0 PyQtWebEngine-5.15.2 PyYAML-5.4.1 absl-py-0.13.0 annolid-1.0.1 cachetools-4.2.2 charset-normalizer-2.0.3 cycler-0.10.0 cython-0.29.24 decord-0.6.0 easydict-1.9 google-auth-1.33.1 google-auth-oauthlib-0.4.4 grpcio-1.39.0 idna-3.2 imgviz-1.2.6 importlib-metadata-4.6.1 kiwisolver-1.3.1 labelme-4.5.9 markdown-3.3.4 matplotlib-3.2.2 numpy-1.21.1 oauthlib-3.1.1 opencv-contrib-python-4.1.2.30 opencv-python-4.1.2.30 opencv-python-headless-4.1.2.30 pandas-1.3.1 protobuf-3.17.3 pyasn1-0.4.8 pyasn1-modules-0.2.8 pycocotools-2.0.2 pyparsing-2.4.7 python-dateutil-2.8.2 pytz-2021.1 qtpy-1.9.0 requests-2.26.0 requests-oauthlib-1.3.0 rsa-4.7.2 scipy-1.7.0 six-1.16.0 tensorboard-2.5.0 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.0 termcolor-1.1.0 torch-1.9.0 torchvision-0.10.0 typing-extensions-3.10.0.0 urllib3-1.26.6 werkzeug-2.0.1 zipp-3.5.0


(annotation) cerebro0@cerebro:~/annolid$ annolid
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (PyQt5 5.14.1 (/usr/lib/python3/dist-packages), Requirement.parse('PyQt5>=5.15.4'), {'PyQtWebEngine'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cerebro0/.local/bin/annolid", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 586, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 599, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'PyQt5>=5.15.4' distribution was not found and is required by PyQtWebEngine
```

**Comment by healthonrails** [comment]
You might need to try  
`conda install -c conda-forge pyside2`
`conda install pyqt`
or 
`pip install pyqt5  # pyqt5 can be installed via pip on python3`.

**Comment by chestonchow** [comment]
I have the same issue
```
hi@hihi:~/annolid$ annolid
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 792, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (PyQt5 5.15.4 (/home/vimana/.local/lib/python3.8/site-packages), Requirement.parse('PyQt5!=5.15.3,!=5.15.4'), {'labelme'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vimana/.local/bin/annolid", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 586, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 599, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'PyQt5!=5.15.3,!=5.15.4' distribution was not found and is required by labelme
```
But with `pip install pyqt5` like what you mentioned, it installs the version of pyqt that it doesn't want
```
hi@hihi:~/annolid$ pip install pyqt5 
Requirement already satisfied: pyqt5 in /home/vimana/.local/lib/python3.8/site-packages (5.15.4)
Requirement already satisfied: PyQt5-Qt5>=5.15 in /home/vimana/.local/lib/python3.8/site-packages (from pyqt5) (5.15.2)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in /home/vimana/.local/lib/python3.8/site-packages (from pyqt5) (12.9.0)
```
Is there any workaround for this?

**Comment by Vignesh1230** [comment]
Echoing @chestonchow 

The proposed fix didn't help.. There seems to be some weird circular dependency problem.
Installing pyqt5 installs the latest version, 5.15.4. The issue is that labelme needs a version _lower_ like 5.15.2.
`The 'PyQt5!=5.15.3,!=5.15.4' distribution was not found and is required by labelme`

So then I went ahead and installed 5.15.2 and ran the command `annolid`, to the result of

`pkg_resources.DistributionNotFound: The 'PyQt5>=5.15.4' distribution was not found and is required by PyQtWebEngine`. 

```
(annotation) cerebro0@cerebro:~/annolid$ pip list
Package                 Version             Location
----------------------- ------------------- ----------------------
absl-py                 0.13.0
annolid                 1.0.1               /home/cerebro0/annolid
cachetools              4.2.2
certifi                 2021.5.30
charset-normalizer      2.0.3
cycler                  0.10.0
Cython                  0.29.24
decord                  0.6.0
easydict                1.9
google-auth             1.33.1
google-auth-oauthlib    0.4.4
grpcio                  1.39.0
idna                    3.2
imgviz                  1.2.6
importlib-metadata      4.6.1
kiwisolver              1.3.1
labelme                 4.5.9
Markdown                3.3.4
matplotlib              3.2.2
numpy                   1.21.1
oauthlib                3.1.1
opencv-contrib-python   4.1.2.30
opencv-python           4.1.2.30
opencv-python-headless  4.1.2.30
pandas                  1.3.1
Pillow                  8.3.1
pip                     21.1.3
protobuf                3.17.3
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pycocotools             2.0.2
pyparsing               2.4.7
PyQt5                   5.15.2
PyQt5-Qt5               5.15.2
PyQt5-sip               12.9.0
PyQtWebEngine           5.15.2
python-dateutil         2.8.2
pytz                    2021.1
PyYAML                  5.4.1
QtPy                    1.9.0
requests                2.26.0
requests-oauthlib       1.3.0
rsa                     4.7.2
scipy                   1.7.0
setuptools              52.0.0.post20210125
six                     1.16.0
tensorboard             2.5.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.0
termcolor               1.1.0
torch                   1.4.0+cpu
torchvision             0.5.0+cpu
typing-extensions       3.10.0.0
urllib3                 1.26.6
Werkzeug                2.0.1
wheel                   0.36.2
zipp                    3.5.0

```

It doesnt make sense that the version is PyQtWebEngine  5.15.2, while simultaneously requesting a version thats 2 newer?

`PyQt5>=5.15.4' distribution was not found and is required by PyQtWebEngine`

Not sure what's happening

**Comment by healthonrails** [comment]
It seems that your env is
using cached PyQtWebEngine-5.15.4-cp36.cp37.cp38.cp39-abi3-manylinux2014_x86_64.whl.
How about try this command `pip install PyQtWebEngine==5.15.2`?
